### ISSUE TITLE
Setting SoL details throws error

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imc-ansible#15]
**IMC version:** 3.0(3a) and 2.0(13e)

When trying to set the serial over lan details using `cisco_imc_sol` module, the playbook throws error.

**Executed the below snippet -**
```
- name: sol setup case1
      cisco_imc_sol:
        speed: 57600
        comport: com0
        ssh_port: 2000
        state: present
        ip: "{{ imc_ip }}"
        username: "{{ imc_username }}"
        password: "{{ imc_password }}"
```

**Observed below error -**
```
fatal: [imc17]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (cisco_imc_sol) module: comport. Supported parameters include: com_port,ip,password,port,proxy,secure,server,server_id,speed,ssh_port,state,username"}
```

Also observed in `cisco_imc_sol.py` that parameter value of `server_id` is mentioned as `read-only, admin, user` instead of `1`.
