### ISSUE TITLE
When tried to run configuring ntp task twice, second time also, 'changed' value is shown as 1

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imc-ansible#16]
**Execute the task twice -** 
```
tasks:
    - name: configure ntp servers
      cisco_imc_ntp:
        state: present
        ntp_servers:
          - {'id': '1', 'ip': '1.1.1.1'}
          - {'id': '2', 'ip': '2.2.2.2'}
          - {'id': '3', 'ip': '3.3.3.3'}
        ip: '{{ imc_ip }}'
        username: '{{ imc_username }}'
        password: '{{ imc_password }}'
```

**After running the second time, below is the output -**
```
ansible-playbook -i inventory create_config/test_create_ntp.yml 

PLAY [imc] **********************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************
ok: [classic_imc16]

TASK [configure ntp servers] ****************************************************************************************************************************
changed: [classic_imc16]

PLAY RECAP **********************************************************************************************************************************************
classic_imc16              : ok=2    changed=1    unreachable=0    failed=0 
```

The changed value should be `0` and not `1`.
