### ISSUE TITLE
Not able to configure ipmi

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imc-ansible#17]
**Run the below task -**
```
tasks:
    - name: enable ipmi case1
      cisco_imc_ipmi:
        state: present
        priv: user
        ip: '{{ imc_ip }}'
        username: '{{ imc_username }}'
        password: '{{ imc_password }}'
```

**Output -**
```
ansible-playbook -i inventory create_config/test_create_ipmi.yml 

PLAY [imc] **********************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************
ok: [classic_imc16]

TASK [enable ipmi case1] ********************************************************************************************************************************
ok: [classic_imc16]

PLAY RECAP **********************************************************************************************************************************************
classic_imc16              : ok=2    changed=0    unreachable=0    failed=0 
```

Nothing changes on the CIMC GUI, tried with priv values `user, admin and read-only`. 
In `cisco_imc_ipmi.py` module, the values of `server_id` are mentioned as `read-only, user and admin`. It should be default value `1`.
